// flow-typed signature: 6754f56b18260b19c07df0b86f9768cd
// flow-typed version: <<STUB>>/eslint-config-vazco_v3.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-vazco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-vazco' {
  declare module.exports: any;
}
