// flow-typed signature: 7db3cda65e161d87dcb70f4d1d43446a
// flow-typed version: <<STUB>>/eslint-plugin-vazco_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vazco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vazco' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vazco/lib/rules/no-console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vazco/index' {
  declare module.exports: $Exports<'eslint-plugin-vazco'>;
}
declare module 'eslint-plugin-vazco/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vazco'>;
}
declare module 'eslint-plugin-vazco/lib/rules/no-console.js' {
  declare module.exports: $Exports<'eslint-plugin-vazco/lib/rules/no-console'>;
}
