// flow-typed signature: eb0830e9e94f023f4356054685d880db
// flow-typed version: <<STUB>>/lerna_v3.5.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna/cli.js' {
  declare module.exports: $Exports<'lerna/cli'>;
}
declare module 'lerna/index' {
  declare module.exports: $Exports<'lerna'>;
}
declare module 'lerna/index.js' {
  declare module.exports: $Exports<'lerna'>;
}
