// flow-typed signature: 689f3d4cfa2944721ccaa0ea9b17c8c2
// flow-typed version: <<STUB>>/simpl-schema_v1.5.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simpl-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simpl-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simpl-schema/dist/clean' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/AutoValueRunner' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/convertToProperType' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/getPositionsForAutoValue' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/setAutoValues' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/defaultMessages' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/doValidation' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/expandShorthand' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/humanize' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/main' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/regExp' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/SimpleSchema' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/SimpleSchemaGroup' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/appendAffectedKey' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/dateToDateString' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/forEachKeyAncestor' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/getKeysWithValueInObj' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/getLastPartOfKey' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/getParentOfKey' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/index' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/isObjectWeShouldTraverse' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/looksLikeModifier' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/allowedValuesValidator' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/requiredValidator' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator/doArrayChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator/doDateChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator/doNumberChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator/doStringChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator/index' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/ValidationContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simpl-schema/dist/clean.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean'>;
}
declare module 'simpl-schema/dist/clean/AutoValueRunner.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/AutoValueRunner'>;
}
declare module 'simpl-schema/dist/clean/convertToProperType.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/convertToProperType'>;
}
declare module 'simpl-schema/dist/clean/getPositionsForAutoValue.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/getPositionsForAutoValue'>;
}
declare module 'simpl-schema/dist/clean/setAutoValues.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/setAutoValues'>;
}
declare module 'simpl-schema/dist/defaultMessages.js' {
  declare module.exports: $Exports<'simpl-schema/dist/defaultMessages'>;
}
declare module 'simpl-schema/dist/doValidation.js' {
  declare module.exports: $Exports<'simpl-schema/dist/doValidation'>;
}
declare module 'simpl-schema/dist/expandShorthand.js' {
  declare module.exports: $Exports<'simpl-schema/dist/expandShorthand'>;
}
declare module 'simpl-schema/dist/humanize.js' {
  declare module.exports: $Exports<'simpl-schema/dist/humanize'>;
}
declare module 'simpl-schema/dist/main.js' {
  declare module.exports: $Exports<'simpl-schema/dist/main'>;
}
declare module 'simpl-schema/dist/regExp.js' {
  declare module.exports: $Exports<'simpl-schema/dist/regExp'>;
}
declare module 'simpl-schema/dist/SimpleSchema.js' {
  declare module.exports: $Exports<'simpl-schema/dist/SimpleSchema'>;
}
declare module 'simpl-schema/dist/SimpleSchemaGroup.js' {
  declare module.exports: $Exports<'simpl-schema/dist/SimpleSchemaGroup'>;
}
declare module 'simpl-schema/dist/utility/appendAffectedKey.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/appendAffectedKey'>;
}
declare module 'simpl-schema/dist/utility/dateToDateString.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/dateToDateString'>;
}
declare module 'simpl-schema/dist/utility/forEachKeyAncestor.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/forEachKeyAncestor'>;
}
declare module 'simpl-schema/dist/utility/getKeysWithValueInObj.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/getKeysWithValueInObj'>;
}
declare module 'simpl-schema/dist/utility/getLastPartOfKey.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/getLastPartOfKey'>;
}
declare module 'simpl-schema/dist/utility/getParentOfKey.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/getParentOfKey'>;
}
declare module 'simpl-schema/dist/utility/index.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/index'>;
}
declare module 'simpl-schema/dist/utility/isObjectWeShouldTraverse.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/isObjectWeShouldTraverse'>;
}
declare module 'simpl-schema/dist/utility/looksLikeModifier.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/looksLikeModifier'>;
}
declare module 'simpl-schema/dist/validation/allowedValuesValidator.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/allowedValuesValidator'>;
}
declare module 'simpl-schema/dist/validation/requiredValidator.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/requiredValidator'>;
}
declare module 'simpl-schema/dist/validation/typeValidator/doArrayChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator/doArrayChecks'>;
}
declare module 'simpl-schema/dist/validation/typeValidator/doDateChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator/doDateChecks'>;
}
declare module 'simpl-schema/dist/validation/typeValidator/doNumberChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator/doNumberChecks'>;
}
declare module 'simpl-schema/dist/validation/typeValidator/doStringChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator/doStringChecks'>;
}
declare module 'simpl-schema/dist/validation/typeValidator/index.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator/index'>;
}
declare module 'simpl-schema/dist/ValidationContext.js' {
  declare module.exports: $Exports<'simpl-schema/dist/ValidationContext'>;
}
